# Homework 0

The goal of this homework is to practice the skills learned in Lecture 2. These skills will be essential for the rest of this course.

Before starting to work on this homework, **make a new folder** named ```hw0-submission```   in your private repo and download ```Homework-0.ipynb``` to that folder.

Let's make sure that you placed everything in the correct folder

In [1]:
import os
error = False

if os.path.basename(os.path.realpath('.')) != "hw0-submission":
    print "The name of the current directory should be 'hw0-submission'"
    error = True

if not error:
    print "You did everything correctly. Congrats!"

You did everything correctly. Congrats!


Now, assuming that everything is in their correct place, you should ``git add`` all the new directories/files and make your initial ```git commit```.

## This is a Markdown cell

In [ ]:
# Insert and edit your own markdown cell *below*. Write your favorite quote

In [2]:
# This is a code cell. Try executing it.
print "hello, data world!"

hello, data world!


Write a function that takes as argument a string and returns its 3-letter suffix. If the string is shorter than 3 letters, return the whole string.

In [14]:
def suffix_3(string):
    if len(string) <= 3:
        return string
    else :
        return string[len(string)-3:len(string)]
    """
    Returns the 3-letter suffix.
    
    Parameters:
        string: str
    
    Returns:
        suffix: str
        If `string` is more than 3-letters long, `suffix` is its 3-letter suffix. Otherwise, `suffix` is the same as `string`.
    """
    

In [17]:
print suffix_3("Hi!")
print suffix_3("Superb")
print suffix_3("123456799")

Hi!
erb
799


When you finish with the above function, don't forget to ```add``` and ```commit``` to your local git repository.

Let's print the versions of some packages that we will be using in the future. If any of these packages are not present, ```conda install``` them.

In [18]:
import numpy
print 'numpy:', numpy.__version__

import scipy
print 'scipy:', scipy.__version__

import matplotlib
print 'matplotlib:', matplotlib.__version__

import sklearn
print 'scikit-learn:', sklearn.__version__

import pandas
print 'pandas:', pandas.__version__

numpy: 1.10.1
scipy: 0.16.0
matplotlib: 1.5.0
scikit-learn: 0.17
pandas: 0.17.1


Write a function that takes as argument a 2D list representing a matrix **M** and returns a boolean indicating whether **M** is an orthogonal matrix.

In [93]:
import numpy

def is_matrix_orthogonal(M):
    #print "debug: transpose\n", numpy.transpose(M)
    
    mul = numpy.dot(M,numpy.transpose(M))
    
    #print "debug mul:\n", mul, len(mul)
    precision = 5e-5 #precision defined as 0.00005 and can be changed 
    return_orth = True
    for i in range (0, len(mul)):
        #check if every [i][i] is 1 and [i][j!=i]=0
        return_orth &= (mul[i][i]<=1.0+precision)&(mul[i][i]>=1.0-precision)
        for j in range (0,len(mul)):
            if i!= j:
                return_orth &= (mul[i][j]<=0.0+precision) & (mul[i][j] >= 0.0-precision)
        #print "debug:\n", mul[i][i], return_orth
        
    return return_orth
    """
    Returns whether M is an orthogonal matrix.
    
    Parameters:
        M: 2D list
    
    Returns:
        is_orthogonal: boolean
    """
    

In [94]:
print is_matrix_orthogonal([[1, 0], [0, -1]])
print is_matrix_orthogonal([[3.3333]])
print is_matrix_orthogonal([[-1.2396, -4.3801, -1.7737], [-1.3121, -2.9193, -4.5496], [-2.1143, 0.0363, 0.2022]])
print is_matrix_orthogonal([[-0.8185, 0.5740, -0.0249], [-0.2510, -0.3183, 0.9142], [-0.5168, -0.7544, -0.4046]])
print is_matrix_orthogonal([[0,-1,1], [1,0,1], [1,0,0]])

debug: transpose
[[ 1  0]
 [ 0 -1]]
debug mul:
[[1 0]
 [0 1]] 2
True
debug: transpose
[[ 3.3333]]
debug mul:
[[ 11.11088889]] 1
False
debug: transpose
[[-1.2396 -1.3121 -2.1143]
 [-4.3801 -2.9193  0.0363]
 [-1.7737 -4.5496  0.2022]]
debug mul:
[[ 23.86789586  22.48293061   2.10324651]
 [ 22.48293061  30.94277906   1.74827332]
 [  2.10324651   1.74827332   4.51246702]] 3
False
debug: transpose
[[-0.8185 -0.251  -0.5168]
 [ 0.574  -0.3183 -0.7544]
 [-0.0249  0.9142 -0.4046]]
debug mul:
[[  1.00003826e+00  -2.42800000e-05   4.97400000e-05]
 [ -2.42800000e-05   1.00007753e+00  -4.30000000e-05]
 [  4.97400000e-05  -4.30000000e-05   9.99902760e-01]] 3
False
debug: transpose
[[ 0  1  1]
 [-1  0  0]
 [ 1  1  0]]
debug mul:
[[2 1 0]
 [1 2 1]
 [0 1 1]] 3
False


When you finish with the above function, don't forget to ```add``` and ```commit``` to your local git repository.

## Submitting

Now, you can push your changes to Github.

In [ ]:
# Code for setting the style of the notebook
from IPython.core.display import HTML
def css_styling():
    styles = open("../../theme/custom.css", "r").read()
    return HTML(styles)
css_styling()